- key:               pivx-testnet
  name:              Pivx Testnet
  client:            pivx                             # API client name.
  server:            http://admin:changeme@127.0.0.1:51475 # Public Pivx node endpoint.
  height:            1087160                               # Initial block number from which sync will be started.
  min_confirmations: 6                                    # Minimal confirmations needed for withdraw and deposit confirmation.
  explorer:
    address:         https://testnet.pivx.link/address/#{addressid}
    transaction:     https://testnet.pivx.link/tx/#{txid}
  status:            active
